- id: docker-mix-credo
  name: mix credo (docker)
  description: Credo.
  language: docker
  entry: /mix.sh credo
  files: \.(exs|ex)$

- id: mix-credo
  name: mix credo
  description: Credo
  language: system
  entry: mix credo --strict
  files: \.(exs|ex)$

- id: docker-mix-format
  name: mix format (docker)
  description: Elixir code format
  language: docker
  entry: /mix.sh
  args: [format]
  files: \.(exs|ex)$

- id: mix-format
  name: mix format
  description: Elixir code format
  language: system
  entry: mix format

- id: docker-mix-test
  name: mix test (docker)
  description: Unit test.
  language: docker
  entry: /mix.sh
  args: [test]
  files: \.(exs|ex)$
  pass_filenames: false

- id: mix-test
  name: mix test
  description: Unit test.
  language: system
  entry: mix test
  files: \.(exs|ex)$
  pass_filenames: false

- id: docker-mix-sobelow
  name: mix sobelow (docker)
  description: Sobelow | Security-focused static analysis for the Phoenix Framework
  language: docker
  entry: /mix.sh
  args: [sobelow]
  pass_filenames: false
  files: \.(exs|ex)$

- id: mix-sobelow
  name: mix sobelow
  description: Sobelow | Security-focused static analysis for the Phoenix Framework
  language: system
  entry: mix sobelow
  pass_filenames: false
  files: \.(exs|ex)$

- id: docker-mix-dialyzer
  name: mix dialyzer (docker)
  description: Dialyzer is a static analysis tool
  language: docker
  entry: /mix.sh
  args: [dialyzer]
  pass_filenames: false
  files: \.(exs|ex)$

- id: mix-dialyzer
  name: mix dializer
  description: Dialyzer is a static analysis tool
  language: system
  entry: mix dialyzer
  pass_filenames: false
  files: \.(exs|ex)$

- id: docker-mix-coverall-html
  name: mix coverall.html (docker)
  description: Test with coverage
  language: docker
  entry: /mix.sh
  args: [coveralls.html]
  pass_filenames: false
  files: \.(exs|ex)$

- id: mix-coverall-html
  name: mix coveralls.html
  description: Test with coverage
  language: system
  entry: mix coveralls.html
  pass_filenames: false
  files: \.(exs|ex)$
