- id: credo
  name: mix credo
  description: Credo.
  language: docker
  entry: /entrypoint.sh credo
  files: \.(exs|ex)$

- id: elixir-lint
  name: lint
  description: Credo.
  language: docker
  entry: /entrypoint.sh mix check
  files: \.(exs|ex)$

- id: elixir-format
  name: format
  description: Credo.
  language: docker
  entry: /entrypoint.sh mix format
  files: \.(exs|ex)$

- id: mix-test
  name: test
  description: Unit test.
  language: docker
  entry: /entrypoint.sh mix test
  files: \.(exs|ex)$
